# Usage:
# make        # compile all binary
# make clean  # remove ALL binaries and objects
# make install  # install binaries

.PHONY = all clean

all:
	cd ./asciied/ && $(MAKE)

clean:
	cd ./asciied/ && $(MAKE) clean

install:
	cd ./asciied/ && $(MAKE) install
